### PR TITLE
Add parent detection

### LINKED ISSUE #299: App Children Not Accounted For
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

For some apps, in particular `dolphin-emu` and `proton-mail`, the children spawned either from the main app, or from the launcher, are not having the same CGroup. Instead, they have the `org.gnome.Shell` CGroup.

### Expected Behavior

Children of a detected app will be counted as part of the app, unless the child is clearly another app.

### Steps To Reproduce

I installed the `proton-mail` deb, and built `dolphin-emu` from source.

### Environment

```markdown
1.5.1, Pop!_OS 22.04 LTS, GNOME 42.9
```

### Anything else?

Mission center, which I think uses parental inheritance, is able to find the children of `proton-mail`, and resources does not detect `dolphin-emu` as an app, despite being in the right cgroup (i think? its in `dolphin-emu`)

### PR DESCRIPTION
**Pull request by jojo2357**
Fixes #299 

before & after. Proton mail has its children accounted for.
image

I've done three things:
 - include parent pid in processdata
 - iff the cgroup is `org.gnome.Shell`, lets try to lookup our parent before invariably being resolved to `org.gnome.Shell`
 - Enabled short-circuiting of the last `some` for performance

I don't expect this to be the final revision, so opening as draft to encourage discussion

### CODE REVIEW

**Comment by nokyan** [comment]
Hi, thanks a lot for the PR!
So far I haven't found anything wrong with it, I've had no false detections when testing around. If you believe it's ready, we can merge it I think. :)

**Comment by jojo2357** [comment]
I worry only that the hardcoded "org.gnome.Shell" will not be useful on other desktop managers.

**Comment by jojo2357** [comment]
Interestingly, my use case appears to have disappeared as Proton Mail is using the correct cgroups now...

**Comment by nokyan** [comment]
> Interestingly, my use case appears to have disappeared as Proton Mail is using the correct cgroups now...

That's interesting indeed. It's still a useful feature though, surely Proton Mail isn't the only app affected by this.

> I worry only that the hardcoded "org.gnome.Shell" will not be useful on other desktop managers.

I think that's okay for now as it doesn't harm Resources on other DEs. I'd export "org.gnome.Shell" into an array to make it easier to extend later. I've got a commit ready, I'd push it to your branch if that's okay with you.

**Comment by jojo2357** [comment]
Go ahead, Im waiting for #305 anyway

**Comment by jojo2357** [comment]
Side-by-side, current flatpak vers is identical to this PR. the other app, `dolphin-emu` seems to have figured itself out (when I move the `.desktop` to a location resources can read)

**Comment by nokyan** [comment]
Do you think this is ready for merging?

**Comment by jojo2357** [comment]
Im not confident to merge this until I can produce a solid example of this working.

I think I will have to design my own app to do it.

**Comment by jojo2357** [comment]
I found a reason, this time with libreoffice

1.6:
image
This branch:
image

**Comment by jojo2357** [comment]
@nokyan do you see any other examples of this PR fixing any apps? if so, and youre fine with the changes, then im fine undrafting and merging.

**Comment by jojo2357** [comment]
Currently rr is committing ~~crimes~~, and i made sure again that it works as advertised.

image

**Comment by nokyan** [comment]
Sorry, I kinda forgot about this PR 😅
Merged. :)

**Pull request merged**
