### PR TITLE
Update Ukrainian translation

### PR DESCRIPTION
**Pull request by Vovkiv**
Added new strings..

Also, could you please provide 2 different contexts for process priority and for updating speed in list of processes/apps?
I don't know about other non-slavic languages, but in Ukrainian (and some other Slavic languages) - "Priority - Very High" become "Пріорітет - Дуже висок`ий`", but "Refresh Speed - Very High" become "Швидкість оновлення - Дуже висок`а`", same for others: "High", "Normal", "Low", "Very Low". In this case, words will change depending on gender that used for this words. This is not the biggest deal, but it looks slightly wrong.

### CODE REVIEW

**Comment by nokyan** [comment]
Hi, thanks for the translation! Of course, I'll add the context shortly, thanks for the heads-up!

**Comment by nokyan** [comment]
Could you quickly check the [`translation-context`](https://github.com/nokyan/resources/tree/translation-context) branch to see if that's correct?

**Comment by Vovkiv** [comment]
Seems fine to me

**Comment by nokyan** [comment]
Great, I'll get the branch merged as quick as possible.

**Comment by Vovkiv** [comment]
Done and tested, works just fine!

**Pull request merged**
