### PR TITLE
More debug statements

### LINKED ISSUE #298: Add debug prints for app detection
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I find that I sometimes am trying to figure out what is going wrong with app detection. (in my case it was that there were two `.desktop` files for the same execuatable, and the wrong (and bad) one was being used and causing the problem.

### Describe the solution you'd like

It would be very nice to have debug prints that explain which `.desktops` were parsed, and what the pertinent values were.

It would be best to have an option to print out the detection results so I can know why a certain process was detected to be a specific app.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nokyan**
Resolves #298

### CODE REVIEW

**Comment by jojo2357** [comment]
Cant build due to errors around `lazy_cell`

**Comment by nokyan** [comment]
> Cant build due to errors around `lazy_cell`

Updating your Rust toolchain should fix this, Rust 1.80 includes LazyLock in std, Resources uses this now instead of lazy_cell.

**Comment by jojo2357** [comment]
`cargo --version`

`cargo 1.80.0 (376290515 2024-07-16)`

**Comment by jojo2357** [comment]
```
error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/utils/settings.rs:12:43
   |
12 | pub static SETTINGS: LazyLock<Settings> = LazyLock::new(Settings::default);
   |                                           ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `resources` (lib) due to 125 previous errors
```

There are obviously a lot of repeated code usages that were omitted for brevity. Im using gnome builder and i tried cleaning, rming the build dir and still nothing

**Comment by nokyan** [comment]
> ```
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/utils/settings.rs:12:43
>    |
> 12 | pub static SETTINGS: LazyLock<Settings> = LazyLock::new(Settings::default);
>    |                                           ^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> For more information about this error, try `rustc --explain E0658`.
> error: could not compile `resources` (lib) due to 125 previous errors
> ```
> 
> There are obviously a lot of repeated code usages that were omitted for brevity. Im using gnome builder and i tried cleaning, rming the build dir and still nothing

I'm not sure but I think GNOME Builder might be using the Flatpak Rust SDK to build Flatpaks, maybe that's the cause. Have you updated `org.freedesktop.Sdk.Extension.rust-stable`?

**Comment by jojo2357** [comment]
Yeah reinstalled SDK's and that did the trick.

Quick impression is that prints when a new app is detected and *why* that process was accepted under that `.desktop` (and maybe the path of that file if applicable)

**Comment by nokyan** [comment]
> Quick impression is that prints when a new app is detected and _why_ that process was accepted under that `.desktop` (and maybe the path of that file if applicable)

Added! I didn't include the path to the .desktop file in the prints for associating a process with an app because that would make those debug statements very verbose in my opinion, but the path to the desktop file is included in the initial app detection debug statements.

**Comment by jojo2357** [comment]
While yes, this is exactly what I asked for, I had envisioned printing only when a *new* app (like a root process, not its children) was detected, since imo children should be accepted nearly automatically to their parent app. 

Firefox gets spammy with all the children it spawns when at the end of the day it is all still ff.

Would it be possible to only print for new apps being detected?

I also noticed that `executable name` matching isn't helpful too much since it is hard to trace that down, could that be logged?

**Comment by nokyan** [comment]
I think only logging some processes could make the logs confusing, one would expect to be all processes logged in my opinion.

> I also noticed that executable name matching isn't helpful too much since it is hard to trace that down, could that be logged?

Do you mean something like this?
image

**Comment by jojo2357** [comment]
I see this

`DEBUG resources::utils::app         > Associating process 4086624 with app "Game 455712169795780630" (ID: discord-455712169795780630) based on process executable name matching with app executable name`

**Comment by nokyan** [comment]
> I see this
> 
> `DEBUG resources::utils::app > Associating process 4086624 with app "Game 455712169795780630" (ID: discord-455712169795780630) based on process executable name matching with app executable name`

Yes, my screenshot was just a quick local change. The executable name is printed at the beginning during the initial app detection though, is this really necessary then?

**Comment by jojo2357** [comment]
Strictly, no, but for convenience, especially if the `.desktop` is quietly overwritten by another `.desktop`, could prove convenient imo

**Comment by nokyan** [comment]
> Strictly, no, but for convenience, especially if the `.desktop` is quietly overwritten by another `.desktop`, could prove convenient imo

Ah, I see. I'll include it then.

**Comment by jojo2357** [comment]
In fact, that overwriting is why my Dolphin install is not detected correctly ;)

**Comment by jojo2357** [comment]
Could you also add the directories scanned for `.desktop`s? Not strictly required, but helpful

**Comment by nokyan** [comment]
> Could you also add the directories scanned for `.desktop`s? Not strictly required, but helpful

Sort of like this?
`DEBUG resources::utils::app    > Using the following directories for app detection: ["/app/share/applications", "/usr/share/applications", "/usr/share/runtime/share/applications", "/run/host/user-share/applications", "/run/host/usr/share/applications", "/run/host/share/applications", "/var/lib/flatpak/exports/share/applications", "/home/nokyan/.local/share/flatpak/exports/share/applications", "/var/lib/snapd/desktop/applications", "/home/nokyan/.local/share/applications"]`

**Comment by jojo2357** [comment]
exactly. then I know why my `.desktop` isnt loaded because `/usr/local/share` isnt scanned

**Comment by nokyan** [comment]
Pushed. :)

**Comment by jojo2357** [comment]
Looks good, now I can actually start to figure stuff out.

**Pull request merged**
