### PR TITLE
Inizale Draft for fixing Usage Problem. No Error Handeling

### PR DESCRIPTION
**Pull request by MythicByte**
Uses then the real Usage value. I have only provided the fix, please correct error handeling. See #412 for more Information about it. The or_else can be there or remove it

### CODE REVIEW

**Comment by nokyan** [comment]
usage_fraction() is supposed to return a fraction between 0.0 and 1.0, the problem was that during the creation of GpuData, it was divided by 100 again, which I have fixed in the `nvidia-usage-fix` branch. The problem also existed for GPUs of other makes, but since for non-NVIDIA cards, the accumulated GPU usage of all processes - which is _not_ erroneously divided by 100 twice - is also considered, it wasn't reflected in the UI.

**Comment by MythicByte** [comment]
When i go home i make the test in #198 and give then feedback.

**Comment by MythicByte** [comment]
> usage_fraction() is supposed to return a fraction between 0.0 and 1.0, the problem was that during the creation of GpuData, it was divided by 100 again, which I have fixed in the `nvidia-usage-fix` branch. The problem also existed for GPUs of other makes, but since for non-NVIDIA cards, the accumulated GPU usage of all processes - which is _not_ erroneously divided by 100 twice - is also considered, it wasn't reflected in the UI. Please see my [newest comment](https://github.com/nokyan/resources/issues/198#issuecomment-2519994082) in #198.

Why not write the branch name in the Devel HeaderBar title, so that it is visible and we don't accidentally test on the wrong branch?

**Comment by nokyan** [comment]
> > usage_fraction() is supposed to return a fraction between 0.0 and 1.0, the problem was that during the creation of GpuData, it was divided by 100 again, which I have fixed in the `nvidia-usage-fix` branch. The problem also existed for GPUs of other makes, but since for non-NVIDIA cards, the accumulated GPU usage of all processes - which is _not_ erroneously divided by 100 twice - is also considered, it wasn't reflected in the UI. Please see my [newest comment](https://github.com/nokyan/resources/issues/198#issuecomment-2519994082) in #198.
> 
> Why not write the branch name in the Devel HeaderBar title, so that it is visible and we don't accidentally test on the wrong branch?

Done. You can also see it in the about dialog.

**Pull request closed without merging**
