### PR TITLE
Round Graph Corners

### LINKED ISSUE #254: Add rounded corners to graphs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Current look:
image-3_orig

Concept look:
image-3_rounded

### Describe alternatives you've considered

Margin graph (labels) need attention, feel cramped

### Additional context

Nice work otherwise, should replace the default system monitor for sure...

### PR DESCRIPTION
**Pull request by jojo2357**
Fixes #254 

Solution: for each ResGraph, add a css class, give that css class rounded corners, and then hide any content of children that is outside the rounded corner.

Marking as draft to force discussion over ideal look and feel.

### CODE REVIEW

**Comment by nokyan** [comment]
Hi, thanks for the PR!
I think it looks good so far but for the smaller graphs in the sidebar and for the thread graphs in the CPU view, a seperate CSS class with a smaller radius would look better I think.

**Comment by jojo2357** [comment]
Done. Feel free to just change the magic numbers. Maybe we change the rounding to be a dynamic unit like `em`? Sounds above my pay grade :P. Marking ready for when you decide on the magic numbers.

**Comment by nokyan** [comment]
I think I've found a sweet spot. :)
I don't know about the `em` thing, I'm not an expert on CSS I have to admit, but this should automatically adjust for other display scalings I believe.

**Comment by jojo2357** [comment]
:rocket:?

I think if it comes up in an issue we can invest more into making the corners more dynamic

**Pull request merged**
