### PR TITLE
Update polish translation

### PR DESCRIPTION
**Pull request by awumii**
For some reason those strings appeared without context, but it seems like they are not used because when i compiled it everything seems to look fine:
obraz
Is it an issue with my translation file? Can i just remove them?

These are the correctly translated:
obraz
obraz

### CODE REVIEW

**Comment by awumii** [comment]
Actually, everything is okay, except for the priority column in the process view. 
obraz

Priority select menu is translated correctly, shouldn't the same strings apply to the column?
obraz

**Comment by nokyan** [comment]
> Actually, everything is okay, except for the priority column in the process view. obraz
> 
> Priority select menu is translated correctly, shouldn't the same strings apply to the column? Maybe they do but my file is broken... obraz

Can you try out the recent commit in `translation-context`? Since process niceness values are "translated" on the fly to labels, I forgot to add the context there.

**Comment by awumii** [comment]
This is fixed now, but the strings remain in the po file, i think the `resources.pot` file needs to be updated
https://github.com/nokyan/resources/blob/ff4f2b99d2e4a55e2df3e248dabe82fb91158bb9/po/resources.pot#L480C19-L498

**Comment by nokyan** [comment]
Updated resources.pot and merged the fixes. :)

**Comment by awumii** [comment]
Okay i think this is ready to merge. I wanted to squash the commits but it seems i have no idea how to do that. Also forgot to sign them, oops..

**Comment by awumii** [comment]
Okay im just gonna open a new pull request....

**Pull request closed without merging**
